### ISSUE TITLE
"Play on Jellyfin" doesn't show up for downloaded media

### ISSUE THREAD

**Issue by zodiacg** [Fallenbagel/jellyseerr#283]
### Description

For requests from the Jellyseerr, only movies are correctly added after being downloaded.
I checked the auto grouping settings according to #255 but still nothing shows up.

I tried manually trigger Jellyfin/Sonarr scan but nothing shows up. According to the logs, Jellyseerr can find the media, but won't update them as playable.

### Version

1.2.1

### Steps to Reproduce

1. Request TV Series/Anime from Jellyseerr
2. Media was downloaded by Sonarr and added to Jellyfin
3. No "Play on Jellyfin" button show up in Jellyseerr

### Logs

```shell
2022-12-24T04:25:00.024Z [info][Jellyfin Sync]: Beginning to process recently added for library: 动漫 
2022-12-24T04:25:12.409Z [info][Jellyfin Sync]: Recently Added Scan Complete 
2022-12-24T04:25:00.076Z [debug][Jellyfin Sync]: Updating existing title: Death Note 
2022-12-24T04:25:04.077Z [info][Jellyfin Sync]: Beginning to process recently added for library: 电影 
2022-12-24T04:25:04.136Z [debug][Jellyfin Sync]: Title already exists and no new media types found Nope 
2022-12-24T04:25:04.146Z [debug][Jellyfin Sync]: Title already exists and no new media types found Minions: The Rise of Gru 
2022-12-24T04:25:04.151Z [debug][Jellyfin Sync]: Title already exists and no new media types found The Unbearable Weight of Massive Talent 
2022-12-24T04:25:08.153Z [info][Jellyfin Sync]: Beginning to process recently added for library: 电视剧 
2022-12-24T04:25:08.215Z [debug][Jellyfin Sync]: Updating existing title: Reborn Rich 
2022-12-24T04:25:08.237Z [debug][Jellyfin Sync]: Updating existing title: The IT Crowd 
2022-12-24T04:25:08.220Z [debug][Jellyfin Sync]: Updating existing title: Only Murders in the Building 
2022-12-24T04:25:08.239Z [debug][Jellyfin Sync]: Updating existing title: The Sandman 
2022-12-24T04:25:08.406Z [debug][Jellyfin Sync]: Saved Somebody Somewhere
```

### Platform

desktop

### Device

PC

### Operating System

Win 10

### Browser

Edge

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
Could you try the `:develop` version? It could be the collection group issue that was solved recently

**Comment by Fallenbagel** [comment]
Could you try the `:develop` version? It could be the collection group issue that was solved recently

**Comment by zodiacg** [comment]
Problem still exists after I switch to the develop version.
I tried a clean install, the problem seems to be partially fixed. The play button is shown for TV series and animes in Jellyfin if I search for them. But only movies are shown under "Recently added".

Here are the logs for the fresh install:
```
2022-12-29T14:08:47.382Z [info][Jellyfin Sync]: Beginning to process library: 电视剧 
2022-12-29T14:08:47.531Z [debug][Jellyfin Sync]: Saved Somebody 
2022-12-29T14:08:47.555Z [debug][Jellyfin Sync]: Saved Reborn Rich 
2022-12-29T14:08:47.633Z [debug][Jellyfin Sync]: Saved Only Murders in the Building 
2022-12-29T14:08:47.634Z [debug][Jellyfin Sync]: Saved Vincenzo 
2022-12-29T14:08:47.634Z [debug][Jellyfin Sync]: Saved The IT Crowd 
2022-12-29T14:08:51.636Z [info][Jellyfin Sync]: Beginning to process library: 动漫 
2022-12-29T14:08:51.731Z [debug][Jellyfin Sync]: Saved Death Note 
2022-12-29T14:08:55.732Z [info][Jellyfin Sync]: Beginning to process library: 电影 
2022-12-29T14:08:55.989Z [debug][Jellyfin Sync]: Saved Minions: The Rise of Gru 
2022-12-29T14:08:55.990Z [debug][Jellyfin Sync]: Saved The Unbearable Weight of Massive Talent 
2022-12-29T14:08:55.990Z [debug][Jellyfin Sync]: Saved The Great Gatsby 
2022-12-29T14:08:55.991Z [debug][Jellyfin Sync]: Saved Nope 
2022-12-29T14:08:56.026Z [debug][Jellyfin Sync]: Saved 365 Days: This Day 
2022-12-29T14:09:00.008Z [debug][Jobs]: Starting scheduled job: Download Sync 
2022-12-29T14:09:00.026Z [info][Jellyfin Sync]: Full Scan Complete 
2022-12-29T14:10:00.007Z [debug][Jobs]: Starting scheduled job: Download Sync 
2022-12-29T14:10:00.012Z [info][Jobs]: Starting scheduled job: Plex Watchlist Sync 
2022-12-29T14:10:00.020Z [info][Jobs]: Starting scheduled job: Jellyfin Recently Added Sync 
2022-12-29T14:10:00.020Z [info][Jellyfin Sync]: Jellyfin Sync Starting {"sessionId":"84c5b0b6-089c-4eaf-a34f-9d241cd1e1ff"}
2022-12-29T14:10:00.024Z [info][Jellyfin Sync]: Beginning to process recently added for library: 电视剧 
2022-12-29T14:10:00.065Z [debug][Jellyfin Sync]: Updating existing title: Reborn Rich 
2022-12-29T14:10:00.066Z [debug][Jellyfin Sync]: Updating existing title: Somebody 
2022-12-29T14:10:00.069Z [debug][Jellyfin Sync]: Updating existing title: Vincenzo 
2022-12-29T14:10:00.078Z [debug][Jellyfin Sync]: Updating existing title: The IT Crowd 
2022-12-29T14:10:04.081Z [info][Jellyfin Sync]: Beginning to process recently added for library: 动漫 
2022-12-29T14:10:04.101Z [debug][Jellyfin Sync]: Updating existing title: Death Note 
2022-12-29T14:10:08.103Z [info][Jellyfin Sync]: Beginning to process recently added for library: 电影 
2022-12-29T14:10:08.161Z [debug][Jellyfin Sync]: Title already exists and no new media types found The Great Gatsby 
2022-12-29T14:10:08.162Z [debug][Jellyfin Sync]: Title already exists and no new media types found 365 Days: This Day 
2022-12-29T14:10:08.163Z [debug][Jellyfin Sync]: Title already exists and no new media types found Nope 
2022-12-29T14:10:08.164Z [debug][Jellyfin Sync]: Title already exists and no new media types found The Unbearable Weight of Massive Talent 
2022-12-29T14:10:08.164Z [debug][Jellyfin Sync]: Title already exists and no new media types found Minions: The Rise of Gru 
2022-12-29T14:10:12.165Z [info][Jellyfin Sync]: Recently Added Scan Complete 
```
It's a bit weird that everything is "saved" in the first sync (during installation), then TV Series and Anime are being "Updated"

**Comment by Fallenbagel** [comment]
Could you show me a screenshot of your jellyfin libraries on both jellyfin tab on jellyseerr and jellyfin dashboard

**Comment by zodiacg** [comment]
The movies are available. It's just there were only movies under the "Recently Added" on the home page.

The libraries and their orders shown in jellyseerr and jellyfin are the same. If I changed the order in Jellyfin and go back to Jellyseerr and click sync libraries, the order in Jellyseerr will be updated to the same as in Jellyfin.

All these being said, they were the observations from 11 hours ago. I just got up and find everything seems to be ok now. Everything downloaded shows up on the home page and available for playing. I'll try getting more information if the same problem occurs later.

**Comment by Fallenbagel** [comment]
> All these being said, they were the observations from 11 hours ago. I just got up and find everything seems to be ok now. Everything downloaded shows up on the home page and available for playing. I'll try getting more information if the same problem occurs later.

Alright. For now I'll close this issue, you can re-open later if you encounter any issues (tho if its about support, we usually provide support on discord only)

**Comment by Fallenbagel** [comment]
> Man I'm having this exact same issue. @Fallenbagel would you prefer I open a fresh issue with fresh logs/screenshots etc or continue this?

Better if you came to discord since this is mostly a troubleshooting error than a bug
