### ISSUE TITLE
Can't link directly to Network page

### ISSUE THREAD

**Issue by cinderblockgames** [Fallenbagel/jellyseerr#395]
### Description

If you click a link to a Network page (e.g., /discover/tv/network/213), it takes you to /login and then to /.

### Version

1.5.0

### Steps to Reproduce

- Copy link to a network (e.g., [your base url]/discover/tv/network/213).
- Paste somewhere.
- Click it.
- End up on the main page.

### Platform

desktop

### Device

Laptop

### Operating System

Manjaro

### Browser

Brave

### Additional Context

If you load Jellyseerr and then paste the URL into the URL bar on the same tab, you can get there directly, but not if you're clicking a link from somewhere else.

### Code of Conduct

- [X] I agree to follow Overseerr's Code of Conduct

**Comment by Fallenbagel** [comment]
This should be fixed with: c84ca4307465af4278f3dad5cf9c2b8cbae3fada

**Comment by Sarin-jacob** [comment]
Still happening . I'm on v1.8.1. Whenever i use any link to jellyseerr content it goes to the login page. This happens mostly when the link originate from another app.. Like email(jellyseerr request notification), telegram etc.

**Comment by Sarin-jacob** [comment]
> @Sarin-jacob can you hop onto discord to troubleshoot this. Because we fixed this recently and I can't reproduce this.

Since this issue was closed, I kinda opened another issue  [#723](https://github.com/Fallenbagel/jellyseerr/issues/723) ..😅
I'm mainly using jellyseerr through chrome, android, and i checked it in desktop too, same issue. 
So should i create a new support post in discord?

**Comment by Fallenbagel** [comment]
> > @Sarin-jacob can you hop onto discord to troubleshoot this. Because we fixed this recently and I can't reproduce this.
> 
> Since this issue was closed, I kinda opened another issue  [#723](https://github.com/Fallenbagel/jellyseerr/issues/723) ..😅
> I'm mainly using jellyseerr through chrome, android, and i checked it in desktop too, same issue. 
> So should i create a new support post in discord? 

Yes. I just tried on my android chrome, opened a link and it went directly to that page
